highlighter: pygments
permalink: /blog/:year-:month-:day/:title
markdown: kramdown

domain: rus.har.mn
description: The personal website and blog of Russell Harmon
#disqus_developer: 1
birthdate: August 9, 1988
disqus_shortname: eatnumber1
twitter_username: eatnumber1
google_latitude_id: 4048757213362106746
google_analytics_id: UA-10349264-2
google_plus_id: 112862864127564162879
sitemap_exclude: /test/

github_username: eatnumber1
github_excludes:
    - eatnumber1.github.com
    - oh-my-zsh
    - dotfiles
    - resume
